version: '2'
services:
    weddingplaner-app:
        image: weddingplaner
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://weddingplaner-mysql:3306/weddingplaner?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=weddingplaner-elasticsearch:9300
        ports:
            - 8080:8080
    weddingplaner-mysql:
        extends:
            file: mysql.yml
            service: weddingplaner-mysql
    weddingplaner-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: weddingplaner-elasticsearch
