version: '2'
services:
    weddingplaner-app:
        image: weddingplaner
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://weddingplaner-postgresql:5432/weddingplaner
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=weddingplaner-elasticsearch:9300
        expose:
            - "8080"
        restart: always
        labels:
            - "traefik.docker.network=web"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:hochzeit.gebsattel.rocks"
            - "traefik.port=8080"
            - "traefik.protocol=http"

    weddingplaner-postgresql:
        extends:
            file: postgresql.yml
            service: weddingplaner-postgresql
    weddingplaner-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: weddingplaner-elasticsearch

volumes:
    postgresql-data:
