version: '2'
services:
    weddingplaner-postgresql:
<<<<<<< HEAD
        image: postgres:9.6.5
        volumes:
            - postgresql-data:/var/lib/postgresql/data/
=======
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/weddingplaner/postgresql/:/var/lib/postgresql/data/
>>>>>>> jhipster_upgrade
        environment:
            - POSTGRES_USER=weddingplaner
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
