version: '2'
services:
    weddingplaner-postgresql:
        image: postgres:10.4
        volumes:
            - postgresql-data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=weddingplaner
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
